apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: problems.problem.io
spec:
  group: problem.io
  names:
    kind: Problem
    listKind: ProblemList
    plural: problems
    singular: problem
  scope: Namespaced
  versions:
    - name: v1alpha3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            a:
              type: object
              properties:
                b:
                  type: object
                  properties:
                    c:
                      type: object
                      properties:
                        d:
                          type: object
                          properties:
                            e:
                              type: object
                              properties:
                                f:
                                  type: object
                                  properties:
                                    g:
                                      type: object
                                      properties:
                                        h:
                                          type: object
                                          properties:
                                            i:
                                              type: array
                                              items:
                                                type: object
                                                properties:
                                                  j:
                                                    type: object
                                                    properties:
                                                      k:
                                                        type: array
                                                        items:
                                                          type: object
                                                          properties:
                                                            l:
                                                              type: array
                                                              items:
                                                                type: string