apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stuck-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: does-not-exist # This ensures the PVC never binds